#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# Claude Master System with Auto Permission Bypass
# Enhanced wrapper with intelligent orchestration and automatic updates
# Auto-generated by Claude Enhanced Installer v2.0
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail

# Configuration
CLAUDE_BINARY="/home/john/.local/bin/claude"
ORCHESTRATOR_PATH="/home/john/claude-backups/agents/src/python/production_orchestrator.py"
CACHE_DIR="$HOME/.cache/claude"
AGENTS_BRIDGE="/home/john/.local/bin/claude-agent"
LEARNING_CLI="/home/john/.local/bin/claude-learning"

# Feature flags - can be disabled via environment variables
CLAUDE_PERMISSION_BYPASS="${CLAUDE_PERMISSION_BYPASS:-true}"
PICMCS_ENABLED="${PICMCS_ENABLED:-false}"
LEARNING_ML_ENABLED="${LEARNING_ML_ENABLED:-false}"
LEARNING_DOCKER_AUTO_START="${LEARNING_DOCKER_AUTO_START:-true}"

# Create cache directory
mkdir -p "$CACHE_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# Logging function
log() {
    echo -e "${CYAN}[Claude Master]${RESET} $1"
}

# Status display
show_status() {
    echo -e "${BOLD}${CYAN}Claude Master System Status:${RESET}"
    echo -e "  ${GREEN}✓${RESET} Claude Binary: $CLAUDE_BINARY"
    echo -e "  ${GREEN}✓${RESET} Permission Bypass: $([[ "$CLAUDE_PERMISSION_BYPASS" == "true" ]] && echo "Enabled" || echo "Disabled")"

    # Check orchestrator
    if [[ -f "$ORCHESTRATOR_PATH" ]]; then
        echo -e "  ${GREEN}✓${RESET} Orchestrator: Available"
    else
        echo -e "  ${YELLOW}⚠${RESET} Orchestrator: Not found"
    fi

    # Check agents bridge
    if [[ -f "$AGENTS_BRIDGE" ]]; then
        echo -e "  ${GREEN}✓${RESET} Agents Bridge: Available"
    else
        echo -e "  ${YELLOW}⚠${RESET} Agents Bridge: Not installed"
    fi

    # Check learning system
    if [[ -f "$LEARNING_CLI" ]]; then
        echo -e "  ${GREEN}✓${RESET} Learning System: Available"
    else
        echo -e "  ${YELLOW}⚠${RESET} Learning System: Not installed"
    fi

    # Check Docker
    if command -v docker >/dev/null && docker ps | grep claude-postgres >/dev/null 2>&1; then
        echo -e "  ${GREEN}✓${RESET} Database: Running (PostgreSQL)"
    else
        echo -e "  ${YELLOW}⚠${RESET} Database: Not running"
    fi
}

# Auto permission bypass check
should_bypass_permissions() {
    # Always bypass if explicitly enabled
    [[ "$CLAUDE_PERMISSION_BYPASS" == "true" ]] && return 0

    # Check for headless/server environment
    if [[ -n "${SSH_CLIENT:-}" ]] || [[ -n "${SSH_TTY:-}" ]] || [[ -f "/.dockerenv" ]]; then
        return 0
    fi

    # Default to no bypass for desktop environments
    return 1
}

# Help display
show_help() {
    cat << 'EOF'
Claude Master System with Auto Permission Bypass
================================================
Commands:
  claude [args]           - Run Claude (with auto permission bypass)
  claude --safe [args]    - Run Claude without permission bypass
  claude --status         - Show status
  claude --list-agents    - List agents
  claude --orchestrator   - Launch Python orchestrator UI

Environment:
  CLAUDE_PERMISSION_BYPASS=false  - Disable auto permission bypass
  PICMCS_ENABLED=false           - Disable PICMCS v3.0 context optimization
  LEARNING_ML_ENABLED=false      - Disable machine learning features
  LEARNING_DOCKER_AUTO_START=true - Enable automatic Docker container startup
EOF
}

# Main command handling
main() {
    # Handle special commands
    case "${1:-}" in
        "--status")
            show_status
            return 0
            ;;
        "--list-agents")
            if [[ -f "$AGENTS_BRIDGE" ]]; then
                "$AGENTS_BRIDGE" list
            else
                echo -e "${YELLOW}⚠${RESET} Agents bridge not installed. Run: python3 claude-enhanced-installer.py --mode=full"
            fi
            return 0
            ;;
        "--orchestrator")
            if [[ -f "$ORCHESTRATOR_PATH" ]]; then
                log "Launching Python orchestrator UI..."
                cd "$(dirname "$ORCHESTRATOR_PATH")"
                python3 "$ORCHESTRATOR_PATH" "${@:2}"
            else
                echo -e "${RED}✗${RESET} Orchestrator not found. Install with: python3 claude-enhanced-installer.py --mode=full"
                return 1
            fi
            return $?
            ;;
        "--help"|"-h")
            show_help
            return 0
            ;;
        "--safe")
            # Run without permission bypass
            shift
            log "Running in safe mode (no permission bypass)"
            exec "$CLAUDE_BINARY" "$@"
            ;;
    esac

    # Verify Claude binary exists
    if [[ ! -f "$CLAUDE_BINARY" ]]; then
        echo -e "${RED}✗${RESET} Claude binary not found at $CLAUDE_BINARY"
        echo "Install Claude with: npm install -g @anthropic-ai/claude-code"
        return 1
    fi

    # Build command with auto permission bypass
    local claude_args=()

    # Add permission bypass if enabled
    if should_bypass_permissions; then
        claude_args+=("--dangerously-skip-permissions")
        log "Auto permission bypass enabled (wayland environment detected)"
    fi

    # Add original arguments
    claude_args+=("$@")

    # Execute Claude with enhanced features
    exec "$CLAUDE_BINARY" "${claude_args[@]}"
}

# Run main function with all arguments
main "$@"
