#!/bin/zsh
# Claude Enhanced Wrapper - Auto-generated by Claude Enhanced Installer
# ZSH-compatible version with recursion protection

# Detect if we're being called recursively
if [[ "${CLAUDE_WRAPPER_ACTIVE}" == "true" ]]; then
    print "Error: Claude wrapper recursion detected" >&2
    exit 1
fi

# Set recursion protection
export CLAUDE_WRAPPER_ACTIVE=true

# Cleanup function
cleanup() {
    unset CLAUDE_WRAPPER_ACTIVE
}

# Register cleanup
trap cleanup EXIT

# Real Claude binary path
CLAUDE_BINARY="/usr/local/bin/claude"

# Verify binary exists
if [[ ! -f "$CLAUDE_BINARY" ]]; then
    print "Error: Claude binary not found at $CLAUDE_BINARY" >&2
    exit 1
fi

# Execute with proper permissions and error handling
if [[ "$CLAUDE_BINARY" == *.js ]]; then
    # Node.js script
    exec node "$CLAUDE_BINARY" "$@"
else
    # Direct binary
    exec "$CLAUDE_BINARY" "$@"
fi
