#!/usr/bin/env python3
"""
Claude NPU Installer Integration
Integrates NPU binary distribution system into the main claude-installer.sh
Creates unified installation that includes NPU bridge as an optional component
"""

import os
import sys
import json
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Any
import logging

# Import our NPU distribution system
from npu_binary_distribution_coordinator import NPUBinaryDistributionCoordinator

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class ClaudeNPUInstallerIntegration:
    """
    Integration layer for NPU binary distribution in Claude installer
    Provides seamless NPU bridge installation as part of Claude setup
    """

    def __init__(self, claude_install_dir: str = None):
        self.claude_install_dir = claude_install_dir or self._detect_claude_install_dir()
        self.npu_enabled = False
        self.installation_results = {}

    def _detect_claude_install_dir(self) -> str:
        """Detect Claude installation directory"""
        # Check common Claude installation paths
        possible_paths = [
            os.path.expanduser("~/.local/share/claude"),
            os.path.expanduser("~/.claude"),
            "/usr/local/share/claude",
            "/opt/claude",
        ]

        for path in possible_paths:
            if Path(path).exists():
                return path

        # Default to user's local share
        return os.path.expanduser("~/.local/share/claude")

    def should_install_npu_bridge(self) -> bool:
        """Determine if NPU bridge should be installed"""
        # Auto-detect Intel NPU
        try:
            from intel_npu_hardware_detector import IntelNPUDetector
            detector = IntelNPUDetector()
            npu = detector.detect_intel_npu()

            if npu:
                logger.info(f"Intel NPU detected: {npu.model_name}")
                return True
            else:
                logger.info("No Intel NPU detected")
                return False
        except Exception as e:
            logger.warning(f"NPU detection failed: {e}")
            return False

    def create_npu_installer_wrapper(self) -> str:
        """Create NPU installer wrapper script"""
        wrapper_content = f'''#!/bin/bash
# NPU Bridge Installer Wrapper
# Generated by Claude NPU Installer Integration

set -euo pipefail

CLAUDE_NPU_DIR="{self.claude_install_dir}/npu"
PYTHON_SCRIPT="{Path(__file__).parent}/npu_binary_distribution_coordinator.py"

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

log() {{ echo -e "${{BLUE}}[NPU-BRIDGE]${{NC}} $1"; }}
warn() {{ echo -e "${{YELLOW}}[WARNING]${{NC}} $1"; }}
error() {{ echo -e "${{RED}}[ERROR]${{NC}} $1"; exit 1; }}
success() {{ echo -e "${{GREEN}}[SUCCESS]${{NC}} $1"; }}

# Check if Python and required modules are available
check_dependencies() {{
    if ! command -v python3 >/dev/null 2>&1; then
        error "Python 3 is required for NPU bridge installation"
    fi

    # Check if our NPU modules are available
    if [[ ! -f "$PYTHON_SCRIPT" ]]; then
        warn "NPU installer script not found, skipping NPU bridge installation"
        exit 0
    fi
}}

# Install NPU bridge
install_npu_bridge() {{
    log "Installing NPU Bridge via Python coordinator..."

    mkdir -p "$CLAUDE_NPU_DIR"

    # Run the Python coordinator
    if python3 "$PYTHON_SCRIPT" \\
        --install-dir "$CLAUDE_NPU_DIR" \\
        --report "$CLAUDE_NPU_DIR/installation-report.json" \\
        --verbose; then

        success "NPU Bridge installed successfully!"

        # Create symlinks in Claude bin directory if needed
        CLAUDE_BIN_DIR="$(dirname "$CLAUDE_NPU_DIR")/bin"
        NPU_BIN_DIR="$CLAUDE_NPU_DIR/bin"

        if [[ -d "$NPU_BIN_DIR" && -d "$CLAUDE_BIN_DIR" ]]; then
            log "Creating symlinks in Claude bin directory..."
            for binary in "$NPU_BIN_DIR"/*; do
                if [[ -x "$binary" ]]; then
                    binary_name=$(basename "$binary")
                    ln -sf "$binary" "$CLAUDE_BIN_DIR/$binary_name" 2>/dev/null || true
                fi
            done
        fi

    else
        warn "NPU Bridge installation failed, continuing without NPU support"
    fi
}}

# Uninstall NPU bridge
uninstall_npu_bridge() {{
    log "Uninstalling NPU Bridge..."

    if [[ -d "$CLAUDE_NPU_DIR" ]]; then
        rm -rf "$CLAUDE_NPU_DIR"
        success "NPU Bridge uninstalled"
    else
        log "NPU Bridge not found"
    fi
}}

# Show NPU status
show_npu_status() {{
    if [[ -d "$CLAUDE_NPU_DIR" && -f "$CLAUDE_NPU_DIR/bin/npu-bridge-server" ]]; then
        log "NPU Bridge Status: INSTALLED"

        # Show version if possible
        if "$CLAUDE_NPU_DIR/bin/npu-bridge-server" --version 2>/dev/null; then
            log "Version check successful"
        else
            warn "Version check failed (may need NPU hardware)"
        fi

        # Show installation report if available
        if [[ -f "$CLAUDE_NPU_DIR/installation-report.json" ]]; then
            log "Installation report available at: $CLAUDE_NPU_DIR/installation-report.json"
        fi
    else
        log "NPU Bridge Status: NOT INSTALLED"
    fi
}}

# Main logic
case "${{1:-install}}" in
    install)
        check_dependencies
        install_npu_bridge
        ;;
    uninstall)
        uninstall_npu_bridge
        ;;
    status)
        show_npu_status
        ;;
    *)
        echo "Usage: $0 {{install|uninstall|status}}"
        echo "  install   - Install NPU Bridge"
        echo "  uninstall - Remove NPU Bridge"
        echo "  status    - Show NPU Bridge status"
        exit 1
        ;;
esac
'''

        wrapper_path = Path(self.claude_install_dir) / "bin" / "claude-npu-installer"
        wrapper_path.parent.mkdir(parents=True, exist_ok=True)

        with open(wrapper_path, 'w') as f:
            f.write(wrapper_content)

        os.chmod(wrapper_path, 0o755)

        logger.info(f"NPU installer wrapper created: {wrapper_path}")
        return str(wrapper_path)

    def integrate_with_claude_installer(self, installer_script_path: str) -> bool:
        """Integrate NPU installation into existing Claude installer"""

        installer_path = Path(installer_script_path)
        if not installer_path.exists():
            logger.error(f"Claude installer not found: {installer_script_path}")
            return False

        # Read current installer
        with open(installer_path, 'r') as f:
            installer_content = f.read()

        # Check if NPU integration already exists
        if "NPU Bridge" in installer_content:
            logger.info("NPU integration already present in installer")
            return True

        # Find insertion point (usually after main Claude installation)
        insertion_marker = "# Installation complete"
        if insertion_marker not in installer_content:
            # Try alternative markers
            alternative_markers = [
                "Installation completed successfully",
                "Claude installed successfully",
                "echo \"Installation complete\"",
                "success \"Installation complete\""
            ]

            insertion_marker = None
            for marker in alternative_markers:
                if marker in installer_content:
                    insertion_marker = marker
                    break

            if not insertion_marker:
                logger.warning("Could not find insertion point in installer")
                return False

        # Create NPU integration snippet
        npu_integration_snippet = f'''

# ═══════════════════════════════════════════════════════════════════════════
# NPU Bridge Integration (Intel Meteor Lake NPU Support)
# ═══════════════════════════════════════════════════════════════════════════

install_npu_bridge_integration() {{
    log "Checking for Intel NPU hardware..."

    # Create NPU installer wrapper
    NPU_WRAPPER="$INSTALL_DIR/bin/claude-npu-installer"

    cat > "$NPU_WRAPPER" << 'EOF'
{self._get_embedded_npu_wrapper()}
EOF

    chmod +x "$NPU_WRAPPER"

    # Check if NPU should be installed
    if python3 -c "
import sys
sys.path.append('{Path(__file__).parent}')
try:
    from intel_npu_hardware_detector import IntelNPUDetector
    detector = IntelNPUDetector()
    npu = detector.detect_intel_npu()
    sys.exit(0 if npu else 1)
except:
    sys.exit(1)
" 2>/dev/null; then
        log "Intel NPU detected - installing NPU Bridge..."

        if "$NPU_WRAPPER" install; then
            success "NPU Bridge installed successfully!"
            log "Use 'claude-npu-installer status' to check NPU Bridge status"
        else
            warn "NPU Bridge installation failed, continuing without NPU support"
        fi
    else
        log "No Intel NPU detected - NPU Bridge available via: claude-npu-installer install"
    fi
}}

# Install NPU integration
install_npu_bridge_integration
'''

        # Insert NPU integration before the completion message
        modified_content = installer_content.replace(
            insertion_marker,
            npu_integration_snippet + "\n" + insertion_marker
        )

        # Write modified installer
        backup_path = installer_path.with_suffix('.sh.backup-pre-npu')
        with open(backup_path, 'w') as f:
            f.write(installer_content)

        with open(installer_path, 'w') as f:
            f.write(modified_content)

        logger.info(f"Claude installer modified with NPU integration")
        logger.info(f"Backup saved to: {backup_path}")

        return True

    def _get_embedded_npu_wrapper(self) -> str:
        """Get embedded NPU wrapper script content"""
        # Read the wrapper we created earlier and return its content
        wrapper_path = Path(self.claude_install_dir) / "bin" / "claude-npu-installer"
        if wrapper_path.exists():
            with open(wrapper_path, 'r') as f:
                return f.read()
        else:
            # Return basic wrapper if file doesn't exist yet
            return f'''#!/bin/bash
# Basic NPU Bridge Installer Wrapper
echo "NPU Bridge installer not fully configured yet"
echo "Run the full Claude installer to complete NPU integration"
'''

    def create_claude_enhanced_wrapper(self) -> str:
        """Create enhanced Claude wrapper with NPU integration"""
        wrapper_content = f'''#!/bin/bash
# Enhanced Claude Wrapper with NPU Bridge Integration
# Automatically routes NPU-related tasks to NPU Bridge

set -euo pipefail

CLAUDE_DIR="{self.claude_install_dir}"
NPU_BRIDGE_SERVER="$CLAUDE_DIR/npu/bin/npu-bridge-server"
ORIGINAL_CLAUDE="$(which claude 2>/dev/null || echo "")"

# Check if this is an NPU-related task
is_npu_task() {{
    local args="$*"
    case "$args" in
        *npu*|*NPU*|*neural*|*inference*|*"machine learning"*|*"ai acceleration"*)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}}

# Route to NPU bridge if appropriate
if is_npu_task "$@" && [[ -x "$NPU_BRIDGE_SERVER" ]]; then
    echo "🧠 Routing to NPU Bridge for neural processing..."
    exec "$NPU_BRIDGE_SERVER" "$@"
elif [[ -n "$ORIGINAL_CLAUDE" ]]; then
    # Use original Claude
    exec "$ORIGINAL_CLAUDE" "$@"
else
    echo "❌ Claude not found in PATH"
    exit 1
fi
'''

        wrapper_path = Path(self.claude_install_dir) / "bin" / "claude-enhanced"
        wrapper_path.parent.mkdir(parents=True, exist_ok=True)

        with open(wrapper_path, 'w') as f:
            f.write(wrapper_content)

        os.chmod(wrapper_path, 0o755)

        logger.info(f"Enhanced Claude wrapper created: {wrapper_path}")
        return str(wrapper_path)

    def setup_npu_integration(self) -> Dict[str, Any]:
        """Set up complete NPU integration"""
        logger.info("Setting up NPU integration for Claude...")

        results = {
            "npu_detected": False,
            "wrapper_created": False,
            "installer_modified": False,
            "enhanced_wrapper_created": False,
            "error": None
        }

        try:
            # Check for NPU
            results["npu_detected"] = self.should_install_npu_bridge()

            # Create NPU installer wrapper
            wrapper_path = self.create_npu_installer_wrapper()
            results["wrapper_created"] = True
            results["wrapper_path"] = wrapper_path

            # Create enhanced Claude wrapper
            enhanced_wrapper = self.create_claude_enhanced_wrapper()
            results["enhanced_wrapper_created"] = True
            results["enhanced_wrapper_path"] = enhanced_wrapper

            # Try to integrate with main installer if it exists
            main_installer = Path(__file__).parent.parent.parent / "claude-installer.sh"
            if main_installer.exists():
                success = self.integrate_with_claude_installer(str(main_installer))
                results["installer_modified"] = success
                if success:
                    results["installer_backup"] = str(main_installer.with_suffix('.sh.backup-pre-npu'))

            logger.info("NPU integration setup completed successfully")

        except Exception as e:
            logger.error(f"NPU integration setup failed: {e}")
            results["error"] = str(e)

        return results

    def install_npu_bridge_now(self, install_dir: str = None) -> bool:
        """Install NPU bridge immediately"""
        install_dir = install_dir or f"{self.claude_install_dir}/npu"

        try:
            coordinator = NPUBinaryDistributionCoordinator(
                install_dir=install_dir
            )

            result = coordinator.run_complete_installation()
            return result.success

        except Exception as e:
            logger.error(f"NPU bridge installation failed: {e}")
            return False

    def generate_integration_report(self) -> Dict[str, Any]:
        """Generate integration status report"""
        claude_dir = Path(self.claude_install_dir)
        npu_dir = claude_dir / "npu"

        report = {
            "claude_dir": str(claude_dir),
            "npu_dir": str(npu_dir),
            "npu_installed": (npu_dir / "bin" / "npu-bridge-server").exists(),
            "wrapper_exists": (claude_dir / "bin" / "claude-npu-installer").exists(),
            "enhanced_wrapper_exists": (claude_dir / "bin" / "claude-enhanced").exists(),
            "installation_report": None
        }

        # Load NPU installation report if available
        npu_report_file = npu_dir / "installation-report.json"
        if npu_report_file.exists():
            try:
                with open(npu_report_file, 'r') as f:
                    report["installation_report"] = json.load(f)
            except (json.JSONDecodeError, IOError):
                pass

        return report


def main():
    """Command-line interface for NPU integration"""
    import argparse

    parser = argparse.ArgumentParser(
        description="Claude NPU Installer Integration"
    )
    parser.add_argument(
        "--claude-dir",
        help="Claude installation directory"
    )
    parser.add_argument(
        "--setup",
        action="store_true",
        help="Set up NPU integration"
    )
    parser.add_argument(
        "--install-npu",
        action="store_true",
        help="Install NPU bridge now"
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="Show integration status"
    )
    parser.add_argument(
        "--report",
        metavar="FILE",
        help="Generate integration report to file"
    )

    args = parser.parse_args()

    integrator = ClaudeNPUInstallerIntegration(args.claude_dir)

    if args.setup:
        print("🔧 Setting up NPU integration...")
        results = integrator.setup_npu_integration()

        if results.get("error"):
            print(f"❌ Setup failed: {results['error']}")
            sys.exit(1)
        else:
            print("✅ NPU integration setup completed")

            if results["npu_detected"]:
                print("🧠 Intel NPU detected")

            if results["wrapper_created"]:
                print(f"📝 NPU installer wrapper: {results.get('wrapper_path')}")

            if results["enhanced_wrapper_created"]:
                print(f"🚀 Enhanced Claude wrapper: {results.get('enhanced_wrapper_path')}")

    elif args.install_npu:
        print("📦 Installing NPU bridge...")
        success = integrator.install_npu_bridge_now()

        if success:
            print("✅ NPU bridge installed successfully")
        else:
            print("❌ NPU bridge installation failed")
            sys.exit(1)

    elif args.status:
        report = integrator.generate_integration_report()
        print("📊 NPU Integration Status:")
        print(f"   Claude Directory: {report['claude_dir']}")
        print(f"   NPU Installed: {'✅' if report['npu_installed'] else '❌'}")
        print(f"   Wrapper Available: {'✅' if report['wrapper_exists'] else '❌'}")
        print(f"   Enhanced Wrapper: {'✅' if report['enhanced_wrapper_exists'] else '❌'}")

    if args.report:
        report = integrator.generate_integration_report()
        with open(args.report, 'w') as f:
            json.dump(report, f, indent=2)
        print(f"📋 Integration report saved to: {args.report}")


if __name__ == "__main__":
    main()