github.com:
    users:
        SWORDIntel:
            oauth_token: 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
    user: SWORDIntel
    oauth_token: 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
