#!/bin/bash
# Phase 3 Universal Optimizer Launcher
# Auto-generated by claude-installer.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_DIR="$PROJECT_ROOT/agents/src/python"

#export PYTHONPATH="$PYTHON_DIR:$PYTHONPATH"

echo "🚀 Phase 3 Universal Optimizer v1.0"
echo "   Location: $PYTHON_DIR"
echo ""

# Check if components exist
missing=()
[[ ! -f "$PYTHON_DIR/phase3-async-integration.py" ]] && missing+=("Async Pipeline")
[[ ! -f "$PYTHON_DIR/team_beta_hardware_acceleration.py" ]] && missing+=("Hardware Acceleration")
[[ ! -f "$PYTHON_DIR/team_gamma_ml_engine.py" ]] && missing+=("ML Engine")
[[ ! -f "$PYTHON_DIR/team_gamma_integration_bridge.py" ]] && missing+=("Integration Bridge")

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "❌ Missing components:"
    for comp in "${missing[@]}"; do
        echo "   - $comp"
    done
    echo ""
    echo "Run: ./claude-installer.sh --with-optimizer to install"
    exit 1
fi

echo "✅ All Phase 3 components present"
echo ""

# Launch Phase 3 system
echo "Starting Phase 3 Universal Optimizer..."
cd "$PYTHON_DIR"

python3 phase3-async-integration.py "$@"
