#!/usr/bin/env python3
"""
Claude Code Integration Installer
Installs and syncs project agents with Claude Code's Task tool system.

This script:
1. Installs the claude_code_integration.py into Claude Code's system
2. Creates proper configuration files
3. Sets up auto-sync for agent updates
4. Verifies integration works correctly
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Optional

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
INTEGRATION_MODULE = PROJECT_ROOT / "src" / "python" / "claude_code_integration.py"


def find_claude_code_installation() -> Optional[Path]:
    """Find Claude Code installation directory."""

    # Common installation paths
    search_paths = [
        Path.home()
        / ".local"
        / "npm-global"
        / "lib"
        / "node_modules"
        / "@anthropic-ai"
        / "claude-code",
        Path("/usr/local/lib/node_modules/@anthropic-ai/claude-code"),
        Path("/opt/claude-code"),
        Path.home()
        / ".npm-global"
        / "lib"
        / "node_modules"
        / "@anthropic-ai"
        / "claude-code",
    ]

    # Check if claude command exists and find its location
    try:
        result = subprocess.run(["which", "claude"], capture_output=True, text=True)
        if result.returncode == 0:
            claude_path = Path(result.stdout.strip())
            if claude_path.exists():
                # Try to find the npm package directory
                possible_root = (
                    claude_path.parent.parent
                    / "lib"
                    / "node_modules"
                    / "@anthropic-ai"
                    / "claude-code"
                )
                if possible_root.exists():
                    search_paths.insert(0, possible_root)
    except:
        pass

    # Check each path
    for path in search_paths:
        if path.exists() and (path / "package.json").exists():
            try:
                with open(path / "package.json") as f:
                    pkg = json.load(f)
                    if pkg.get("name") == "@anthropic-ai/claude-code":
                        return path
            except:
                continue

    return None


def install_integration_module(claude_code_path: Path) -> bool:
    """Install our integration module into Claude Code's system."""

    try:
        # Create extensions directory if it doesn't exist
        extensions_dir = claude_code_path / "extensions"
        extensions_dir.mkdir(exist_ok=True)

        # Copy our integration module
        target_file = extensions_dir / "project_agents.py"
        shutil.copy2(INTEGRATION_MODULE, target_file)

        print(f"✓ Installed integration module: {target_file}")
        return True

    except Exception as e:
        print(f"✗ Failed to install integration module: {e}")
        return False


def create_config_files() -> bool:
    """Create Claude Code configuration files."""

    try:
        # Import our integration module to get agent definitions
        sys.path.insert(0, str(PROJECT_ROOT / "src" / "python"))
        from claude_code_integration import PROJECT_AGENTS, create_claude_config

        # Create configuration
        config_file = create_claude_config()
        print(f"✓ Created agent configuration: {config_file}")

        # Create environment setup script
        config_dir = Path.home() / ".config" / "claude"
        setup_script = config_dir / "activate-project-agents.sh"

        script_content = f"""#!/bin/bash
# Activate Project Agents for Claude Code
# Auto-generated by claude-installer

export CLAUDE_CUSTOM_AGENTS="{config_file}"
export CLAUDE_AGENTS_ROOT="{PROJECT_ROOT / 'agents'}"
export PYTHONPATH="{PROJECT_ROOT}:$PYTHONPATH"

# Create symbolic links for agent access
for agent in {' '.join(PROJECT_AGENTS.keys())}; do
    export CLAUDE_AGENT_${{agent^^}}="available"
done

echo "✓ Project agents activated ({len(PROJECT_AGENTS)} agents)"
echo "  Run 'claude' to use with Task tool support"
"""

        with open(setup_script, "w") as f:
            f.write(script_content)

        setup_script.chmod(0o755)
        print(f"✓ Created activation script: {setup_script}")

        return True

    except Exception as e:
        print(f"✗ Failed to create config files: {e}")
        return False


def setup_auto_sync() -> bool:
    """Set up automatic sync of agent updates."""

    try:
        # Create sync script
        sync_script = PROJECT_ROOT / "scripts" / "sync-claude-agents.sh"
        sync_script.parent.mkdir(exist_ok=True)

        script_content = f"""#!/bin/bash
# Auto-sync project agents with Claude Code
# Called by git hooks and installers

cd "{PROJECT_ROOT}"

echo "Syncing project agents with Claude Code..."

# Run the integration installer
python3 "{PROJECT_ROOT}/agents/src/python/install_claude_integration.py" --quiet

# Update agent registry
python3 -c "
import sys
sys.path.insert(0, '{PROJECT_ROOT}/agents/src/python')
from claude_code_integration import create_claude_config
create_claude_config()
print('✓ Agent registry updated')
"

echo "✓ Claude Code agent sync complete"
"""

        with open(sync_script, "w") as f:
            f.write(script_content)

        sync_script.chmod(0o755)
        print(f"✓ Created sync script: {sync_script}")

        # Add to git hooks if in a git repository
        git_dir = PROJECT_ROOT / ".git"
        if git_dir.exists():
            post_commit_hook = git_dir / "hooks" / "post-commit"

            hook_content = f"""#!/bin/bash
# Auto-sync agents after commits
"{sync_script}" >/dev/null 2>&1 &
"""

            if not post_commit_hook.exists():
                with open(post_commit_hook, "w") as f:
                    f.write(hook_content)
                post_commit_hook.chmod(0o755)
                print("✓ Added git post-commit hook for auto-sync")

        return True

    except Exception as e:
        print(f"✗ Failed to setup auto-sync: {e}")
        return False


def verify_integration() -> bool:
    """Verify that the integration works correctly."""

    try:
        # Test agent availability
        sys.path.insert(0, str(PROJECT_ROOT / "src" / "python"))
        from claude_code_integration import get_agent_info, get_available_agents

        agents = get_available_agents()
        print(f"✓ Verified {len(agents)} agents available")

        # Test a few key agents
        test_agents = ["planner", "director", "security", "architect"]
        for agent in test_agents:
            if agent in agents:
                info = get_agent_info(agent)
                if info:
                    print(f"  ✓ {agent.upper()}: {info['description'][:50]}...")

        return True

    except Exception as e:
        print(f"✗ Integration verification failed: {e}")
        return False


def main():
    """Main installation function."""

    print("🚀 Installing Claude Code Project Agent Integration")
    print("=" * 60)

    # Check if running with --quiet flag
    quiet = "--quiet" in sys.argv

    if not quiet:
        print(f"Project root: {PROJECT_ROOT}")
        print(f"Integration module: {INTEGRATION_MODULE}")

    # Find Claude Code installation
    claude_code_path = find_claude_code_installation()
    if not claude_code_path:
        print("✗ Claude Code installation not found")
        print(
            "  Please install Claude Code first: npm install -g @anthropic-ai/claude-code"
        )
        return False

    if not quiet:
        print(f"✓ Found Claude Code installation: {claude_code_path}")

    # Install integration module
    if not install_integration_module(claude_code_path):
        return False

    # Create configuration files
    if not create_config_files():
        return False

    # Setup auto-sync
    if not setup_auto_sync():
        return False

    # Verify integration
    if not verify_integration():
        return False

    if not quiet:
        print("\n🎉 Installation Complete!")
        print("=" * 60)
        print("Your project agents are now integrated with Claude Code's Task tool.")
        print("\nUsage examples:")
        print("  Task(subagent_type='planner', prompt='Create project roadmap')")
        print("  Task(subagent_type='security', prompt='Perform security audit')")
        print("  Task(subagent_type='architect', prompt='Design system architecture')")
        print("\nTo activate the agents in your shell:")
        print("  source ~/.config/claude/activate-project-agents.sh")

    return True


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
