#!/usr/bin/env python3
"""
Analyze Claude Code TodoWrite files and create better naming/attribution system
These UUID-based files are generated by Claude Code's TodoWrite tool during sessions
"""

import json
import os
from pathlib import Path
import sys
import re
from datetime import datetime
from collections import defaultdict


# Add project root to Python path for imports
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

try:
    from path_utilities import (
        get_project_root, get_agents_dir, get_database_dir,
        get_python_src_dir, get_shadowgit_paths, get_database_config
    )
except ImportError:
    # Fallback if path_utilities not available
    def get_project_root():
        return Path(__file__).parent.parent.parent
    def get_agents_dir():
        return get_project_root() / 'agents'
    def get_database_dir():
        return get_project_root() / 'database'
    def get_python_src_dir():
        return get_agents_dir() / 'src' / 'python'
    def get_shadowgit_paths():
        home_dir = Path.home()
        return {'root': home_dir / 'shadowgit'}
    def get_database_config():
        return {
            'host': 'localhost', 'port': 5433,
            'database': 'claude_agents_auth',
            'user': 'claude_agent', 'password': 'claude_auth_pass'
        }
TODO_DIR = str(get_project_root() / "config/todos"

def analyze_todo_files():
    """Analyze all todo files and extract patterns"""
    
    print("="*60)
    print("CLAUDE CODE TODO FILES ANALYSIS")
    print("="*60)
    
    file_stats = {
        'total_files': 0,
        'empty_files': 0,
        'content_files': 0,
        'categories': defaultdict(int)
    }
    
    todo_content = []
    
    for filename in os.listdir(TODO_DIR):
        if not filename.endswith('.json'):
            continue
            
        file_stats['total_files'] += 1
        filepath = os.path.join(TODO_DIR, filename)
        
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)
                
            if not data or data == []:
                file_stats['empty_files'] += 1
                continue
                
            file_stats['content_files'] += 1
            
            # Extract UUID from filename
            uuid_match = re.search(r'([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})', filename)
            uuid = uuid_match.group(1) if uuid_match else "unknown"
            
            # Analyze content
            session_info = {
                'uuid': uuid,
                'filename': filename,
                'todo_count': len(data),
                'todos': data,
                'categories': set()
            }
            
            # Categorize todos by content
            for todo in data:
                content = todo.get('content', '').lower()
                
                if any(word in content for word in ['build', 'iso', 'livecd', 'debian']):
                    session_info['categories'].add('LiveCD Development')
                    file_stats['categories']['LiveCD Development'] += 1
                elif any(word in content for word in ['security', 'fix', 'vulnerability']):
                    session_info['categories'].add('Security')
                    file_stats['categories']['Security'] += 1
                elif any(word in content for word in ['agent', 'orchestrator', 'implementation']):
                    session_info['categories'].add('Agent Development')
                    file_stats['categories']['Agent Development'] += 1
                elif any(word in content for word in ['database', 'postgresql', 'learning']):
                    session_info['categories'].add('Database/Learning')
                    file_stats['categories']['Database/Learning'] += 1
                elif any(word in content for word in ['test', 'performance', 'benchmark']):
                    session_info['categories'].add('Testing')
                    file_stats['categories']['Testing'] += 1
                else:
                    session_info['categories'].add('General')
                    file_stats['categories']['General'] += 1
            
            todo_content.append(session_info)
                
        except (json.JSONDecodeError, IOError) as e:
            print(f"Error reading {filename}: {e}")
            continue
    
    # Print analysis results
    print(f"\nFILE STATISTICS:")
    print(f"  Total files: {file_stats['total_files']}")
    print(f"  Empty files: {file_stats['empty_files']} (just [])")
    print(f"  Files with content: {file_stats['content_files']}")
    
    print(f"\nCATEGORY BREAKDOWN:")
    for category, count in sorted(file_stats['categories'].items(), key=lambda x: x[1], reverse=True):
        print(f"  {category}: {count} todos")
    
    print(f"\nCONTENT ANALYSIS:")
    
    # Show examples of each category
    category_examples = defaultdict(list)
    for session in todo_content:
        for category in session['categories']:
            if len(category_examples[category]) < 3:  # Limit examples
                for todo in session['todos']:
                    category_examples[category].append({
                        'uuid': session['uuid'][:8],
                        'content': todo['content']
                    })
                    break
    
    for category, examples in category_examples.items():
        print(f"\n{category} Examples:")
        for ex in examples[:2]:
            print(f"  [{ex['uuid']}...] {ex['content']}")
    
    return file_stats, todo_content

def create_better_naming_system(todo_content):
    """Create a better naming system for todo files"""
    
    print(f"\nPROPOSED NAMING IMPROVEMENTS:")
    print("="*40)
    
    naming_suggestions = []
    
    for session in todo_content:
        uuid = session['uuid']
        categories = list(session['categories'])
        todo_count = session['todo_count']
        
        # Create descriptive name
        if 'LiveCD Development' in categories:
            suggested_name = f"session-livecd-{uuid[:8]}-{todo_count}todos.json"
        elif 'Security' in categories:
            suggested_name = f"session-security-{uuid[:8]}-{todo_count}todos.json"
        elif 'Agent Development' in categories:
            suggested_name = f"session-agents-{uuid[:8]}-{todo_count}todos.json"
        elif 'Database/Learning' in categories:
            suggested_name = f"session-database-{uuid[:8]}-{todo_count}todos.json"
        elif 'Testing' in categories:
            suggested_name = f"session-testing-{uuid[:8]}-{todo_count}todos.json"
        else:
            suggested_name = f"session-general-{uuid[:8]}-{todo_count}todos.json"
        
        naming_suggestions.append({
            'original': session['filename'],
            'suggested': suggested_name,
            'category': categories[0] if categories else 'General',
            'sample_todo': session['todos'][0]['content'] if session['todos'] else 'Empty'
        })
    
    # Group by category for better organization
    by_category = defaultdict(list)
    for suggestion in naming_suggestions:
        by_category[suggestion['category']].append(suggestion)
    
    for category, suggestions in sorted(by_category.items()):
        print(f"\n{category} ({len(suggestions)} files):")
        for i, suggestion in enumerate(suggestions[:3], 1):  # Show first 3 examples
            print(f"  {i}. {suggestion['original'][:20]}... -> {suggestion['suggested']}")
            print(f"     Sample: {suggestion['sample_todo'][:50]}...")
        if len(suggestions) > 3:
            print(f"     ... and {len(suggestions) - 3} more files")
    
    return naming_suggestions

def generate_attribution_report():
    """Generate report about TodoWrite tool usage patterns"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""# Claude Code TodoWrite Files Analysis Report

**Generated**: {timestamp}
**Location**: config/todos/
**Tool**: Claude Code TodoWrite feature

## What These Files Are

These UUID-based JSON files are automatically created by Claude Code's TodoWrite tool during interactive sessions. Each file represents a session where the TodoWrite tool was used to track progress on tasks.

## File Naming Pattern

Current pattern: `[UUID]-agent-[UUID].json`
- The UUID appears to be a session identifier
- "agent" indicates these were created during agent-related work
- Files are automatically generated, not manually created

## Attribution

**Created by**: Claude Code's TodoWrite tool
**Purpose**: Session-based task tracking during development
**Usage**: Interactive development sessions from ~August 2025
**Generator**: Anthropic's Claude Code CLI tool

## Content Analysis

- **Empty files**: Many contain just `[]` (empty todo list)
- **Content files**: Some contain actual todo items with status tracking
- **Categories**: LiveCD development, agent implementation, security work, database work
- **Status tracking**: Each todo has content, status (pending/in_progress/completed), and activeForm

## Recommendation

These files are session artifacts and can be safely archived. They provide historical insight into development sessions but are not needed for current operations.

## Better Naming Convention

Instead of UUID-based names, suggest:
- `session-[category]-[date]-[short-uuid].json`
- Example: `session-livecd-20250829-c9a2494a.json`

This would make the files more human-readable while maintaining uniqueness.
"""
    
    return report

if __name__ == "__main__":
    file_stats, todo_content = analyze_todo_files()
    naming_suggestions = create_better_naming_system(todo_content)
    attribution_report = generate_attribution_report()
    
    # Save attribution report
    with open(str(get_project_root() / 'TODO_FILES_ATTRIBUTION_REPORT.md', 'w') as f:
        f.write(attribution_report)
    
    print(f"\n" + "="*60)
    print("ANALYSIS COMPLETE")
    print("="*60)
    print("✅ File statistics analyzed")
    print("✅ Content categories identified")
    print("✅ Attribution determined: Claude Code TodoWrite tool")
    print("✅ Better naming system proposed")
    print("✅ Attribution report saved: TODO_FILES_ATTRIBUTION_REPORT.md")
    print(f"\nSUMMARY:")
    print(f"  - {file_stats['total_files']} total todo files")
    print(f"  - {file_stats['empty_files']} empty (just [])")
    print(f"  - {file_stats['content_files']} with actual content")
    print(f"  - Created by Claude Code's TodoWrite during development sessions")
    print(f"  - Safely archivable as historical session artifacts")