#!/usr/bin/env python3
"""
Setup script for manage_environment
Generated by PYTHON-INTERNAL Agent vv1.0.0
"""

from setuptools import setup, find_packages

setup(
    name="manage-environment",
    version="1.0.0",
    author="PYTHON-INTERNAL Agent",
    author_email="agent@claude.ai",
    description="Python package for manage_environment operations",
    long_description=open("README.md").read() if Path("README.md").exists() else "",
    long_description_content_type="text/markdown",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "requests>=2.31.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "black>=23.0.0",
            "mypy>=1.5.0",
        ],
        "profiling": [
            "memory-profiler>=0.61.0",
            "line-profiler>=4.0.0",
        ]
    },
    entry_points={
        "console_scripts": [
            "manage_environment-cli=manage.environment.cli:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
