#!/bin/bash
# Local Opus Server Startup Script
# Generated by Claude Military Installer

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_OPUS_DIR="$SCRIPT_DIR/local-models/opus-openvino"

echo "🚀 Starting Local Opus Inference Server"
echo "   Directory: $LOCAL_OPUS_DIR"
echo "   Server: http://localhost:8000"
echo "   Zero-token local inference for 98-agent system"
echo ""

cd "$LOCAL_OPUS_DIR"

# Check if server file exists
if [ ! -f "local_opus_server.py" ]; then
    echo "❌ Error: local_opus_server.py not found"
    exit 1
fi

# Install dependencies if needed
if ! python3 -c "import fastapi" 2>/dev/null; then
    echo "📦 Installing FastAPI dependencies..."
    pip3 install fastapi uvicorn pydantic
fi

# Start server
echo "🎯 Launching server on localhost:8000..."
python3 local_opus_server.py

echo "🏁 Local Opus server stopped"
